on: push

jobs:
    project-a-or-project-b:
        runs-on: ubuntu-latest
        name: Project A or Project B
        outputs:
            output1: ${{ steps.main.outputs.OUTPUT }}
        steps:

        - name: Checkout Main repository
          uses: actions/checkout@v2
          with:
            path: ./mainRepository
    
        - uses: actions/setup-go@v1
          with:
            go-version: '1.9.3' # The Go version to download (if necessary) and use.

        - name: Run Main Repository 
          id: main
          run: |
            cd ./mainRepository &&
            go run main.go &&
            OUTPUT=$(exif ... | tail -1) &&
            echo "::set-output name=OUTPUT::$OUTPUT"
    
    run-project:
        runs-on: ubuntu-latest
        needs: project-a-or-project-b
        name: Run the Project
        
        steps:

        - name: Run Project A
          if: ${{needs.project-a-or-project-b.outputs.output1}} == 0
          run: |
            cd ./mainRepository/projectA &&
            go run main.go
        
        - name: Run Project B
            if: ${{needs.project-a-or-project-b.outputs.output1}} == 1
            run: |
              cd ./mainRepository/projectB &&
              go run main.go
